### ISSUE TITLE
creation maquette

### ISSUE THREAD

**Issue by antoine13330** [antoine13330/Colink-Front#3]
- [ ] integrer lien figma dans le parent #2 
- [ ] login
- [ ] register
- [ ] mdp oublié 
- [ ] profil management #8 
- [ ] profil user ( visualiser les informations public d'un utilisateur )  
- [ ] liste des projets #13 
- [ ] projet detail #11 #12 
- [ ] dashboard des projets #14
